function [beta] = RBF_OnlineInterpolation(ROM, mu)
%RBF_ONLINEINTERPOLATION online evaluation of the RBF interpolant of the
%stability factor
%
%   [BETA] = RBF_ONLINEINTERPOLATION(ROM, MU) given a ROM struct containing
%   a stabFactor field generated by RBF_OFFLINEINTERPOLATION, computes the 
%   RBF interpolant BETA of the stability factor at MU

%   This file is part of redbKIT.
%   Copyright (c) 2015, Ecole Polytechnique Federale de Lausanne (EPFL)
%   Author: Federico Negri <federico.negri at epfl.ch> 


mu_HyperCube =  RBF_transformUnit(mu(:,ROM.stabFactor.mu_interp_index),...
                    ROM.stabFactor.mu_MapToUnit(ROM.stabFactor.mu_interp_index,:))';

log_beta     =  RBF_evaluate(mu_HyperCube, ROM.stabFactor.Interpolant_data);

beta         =  exp(log_beta); 


end