mkdir depTool;

url_dep = 'https://www.mathworks.com/matlabcentral/mlc-downloads/downloads/submissions/27787/versions/1/download/zip';

unzip(url_dep, 'depTool');

cd depTool/dep;

mkdir FEM_library_AllFiles;

!find ../../FEM_library/ -type f -exec cp '{}' ./FEM_library_AllFiles/ \;


mkdir DepGraphs;

dep('FEM_library_AllFiles','FEM_library_AllFiles/CSMt_Solver.m',2,[],'DepGraphs/CSMt_Solver_Dep')
dep('FEM_library_AllFiles','FEM_library_AllFiles/CSM_Solver.m',2,[],'DepGraphs/CSM_Solver_Dep')
dep('FEM_library_AllFiles','FEM_library_AllFiles/NS_Solver.m',2,[],'DepGraphs/NS_Solver_Dep')
dep('FEM_library_AllFiles','FEM_library_AllFiles/NSt_Solver.m',2,[],'DepGraphs/NSt_Solver_Dep')
dep('FEM_library_AllFiles','FEM_library_AllFiles/FSIt_Solver.m',2,[],'DepGraphs/FSIt_Solver_Dep')

dep('FEM_library_AllFiles','FEM_library_AllFiles/Elliptic_Solver.m',2,[],'DepGraphs/Elliptic_Solver_Dep')
dep('FEM_library_AllFiles','FEM_library_AllFiles/ADRt_Solver.m',2,[],'DepGraphs/ADRt_Solver_Dep')


%% MODIFIED VERSION of dot.sh
%==========================================================================
% #!/bin/bash
% 
% # omit repeated lines (otherwise the graph is bad)
% perl -n -e 'print unless $h{$_}++' deptmp/graph.dot > deptmp/uniq.dot
% # if you dont't have perl, you can use (warning change the order of the lines)
% # sort deptmp/graph.dot >  deptmp/sort.dot
% # uniq deptmp/sort.dot >  deptmp/uniq.dot
% 
% # put the header for the .dot file
% echo "/* Generated by dep */" > $1.dot
% echo "digraph dep {" >> $1.dot
% echo "    node [shape = box];" >> $1.dot
% echo "    rankdir=LR ;" >> $1.dot
% 
% # other options
% # fontsize = 360;
% # orientation=landscape;
% # ratio=fill;
% # size="11,7";
% # node [shape = box, style = filled,peripheries=1,fontsize=80];
% # nodesep=0.9;
% # ranksep=2;
% 
% # put the content
% cat deptmp/uniq.dot >> $1.dot
% 
% # end of the .dot file
% echo "}" >> $1.dot
% 
% # run dot
% dot -Tpdf $1.dot -o $1.pdf
% dot -Tpng $1.dot -o $1.png
% 
% exit 0;

%==========================================================================