function CSM_export_VonMisesStress(dim, VM_Stress, vertices, elements, outputFileName, iter, variableName)
%CSM_EXPORT_VONMISESSTRESS export a (P1) Cell-Based VM stress to vtk (binary) file

%   This file is part of redbKIT.
%   Copyright (c) 2016, Ecole Polytechnique Federale de Lausanne (EPFL)
%   Author: Federico Negri <federico.negri at epfl.ch> 

titleData = 'CSM_VMstress';
if nargin < 6
      iter = -1;
end

if nargin < 7
      variableName = 'VonMisesStress';
end

if dim == 2
      
      exportData = struct('iteration', {iter},...
            'vertices', {vertices'},...
            'elements', {elements(1:3,:)'},...
            'outputFile', {outputFileName},...
            'title', {titleData},...
            'variableName',{{variableName}},...
            'variableType',{{'SCALARS'}},...
            'variableData',{{VM_Stress'}});
      
      exporter2dVTK_cell(exportData);
      
elseif dim == 3
      
      exportData=struct('iteration', {iter},...
            'vertices', {vertices'},...
            'elements', {elements(1:4,:)'},...
            'outputFile', {outputFileName},...
            'title', {titleData},...
            'variableName',{{variableName}},...
            'variableType',{{'SCALARS'}},...
            'variableData',{{VM_Stress'}});
        
      exporter3dVTK_cell(exportData);
end
